name: Zephyr main Branch Integration
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Every day

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: otterpill_zephyr

      - name: Initialize
        working-directory: otterpill_zephyr
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build blinky sample for otterpill
        #working-directory: example-application
        run: |
          west twister --build-only --inline-logs --test samples/basic/blinky/sample.basic.blinky --platform otterpill
